// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: arith.proto

package mygrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArithClient is the client API for Arith service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArithClient interface {
	Multiply(ctx context.Context, in *Param, opts ...grpc.CallOption) (*Int, error)
	Divide(ctx context.Context, in *Param, opts ...grpc.CallOption) (*Quotient, error)
}

type arithClient struct {
	cc grpc.ClientConnInterface
}

func NewArithClient(cc grpc.ClientConnInterface) ArithClient {
	return &arithClient{cc}
}

func (c *arithClient) Multiply(ctx context.Context, in *Param, opts ...grpc.CallOption) (*Int, error) {
	out := new(Int)
	err := c.cc.Invoke(ctx, "/Arith/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithClient) Divide(ctx context.Context, in *Param, opts ...grpc.CallOption) (*Quotient, error) {
	out := new(Quotient)
	err := c.cc.Invoke(ctx, "/Arith/Divide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArithServer is the server API for Arith service.
// All implementations must embed UnimplementedArithServer
// for forward compatibility
type ArithServer interface {
	Multiply(context.Context, *Param) (*Int, error)
	Divide(context.Context, *Param) (*Quotient, error)
	mustEmbedUnimplementedArithServer()
}

// UnimplementedArithServer must be embedded to have forward compatible implementations.
type UnimplementedArithServer struct {
}

func (UnimplementedArithServer) Multiply(context.Context, *Param) (*Int, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedArithServer) Divide(context.Context, *Param) (*Quotient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Divide not implemented")
}
func (UnimplementedArithServer) mustEmbedUnimplementedArithServer() {}

// UnsafeArithServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArithServer will
// result in compilation errors.
type UnsafeArithServer interface {
	mustEmbedUnimplementedArithServer()
}

func RegisterArithServer(s grpc.ServiceRegistrar, srv ArithServer) {
	s.RegisterService(&Arith_ServiceDesc, srv)
}

func _Arith_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Param)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Arith/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithServer).Multiply(ctx, req.(*Param))
	}
	return interceptor(ctx, in, info, handler)
}

func _Arith_Divide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Param)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithServer).Divide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Arith/Divide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithServer).Divide(ctx, req.(*Param))
	}
	return interceptor(ctx, in, info, handler)
}

// Arith_ServiceDesc is the grpc.ServiceDesc for Arith service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Arith_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Arith",
	HandlerType: (*ArithServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiply",
			Handler:    _Arith_Multiply_Handler,
		},
		{
			MethodName: "Divide",
			Handler:    _Arith_Divide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arith.proto",
}
